// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// DATABASE_PROVIDER chooses which datasource (and therefore which migration
// set) Prisma operates on:
//   - sqlite      -> prisma/schema.prisma + prisma/migrations      (local dev/tests)
//   - postgresql  -> prisma/schema.postgres.prisma + prisma/postgres-migrations
//                    (Supabase / production)
export default defineConfig({
  schema:
    process.env["DATABASE_PROVIDER"] === "postgresql"
      ? "prisma/schema.postgres.prisma"
      : "prisma/schema.prisma",
  migrations: {
    path:
      process.env["DATABASE_PROVIDER"] === "postgresql"
        ? "prisma/postgres-migrations"
        : "prisma/migrations",
  },
  datasource: {
    // Falls back to the local SQLite dev database so `prisma generate` works
    // in build environments (e.g. Render) that have no DATABASE_URL set yet.
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});