// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Falls back to the local SQLite dev database so `prisma generate` works
    // in build environments (e.g. Render) that have no DATABASE_URL set yet.
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
